import {mockIp, mockReqId} from '../../utils/mock';

export function genOrders(params) {
    const resp = {
        data: {
            pageNum: 1,
            pageSize: 10,
            totalCount: 7,
            orders: [
                {
                    orderId: '354021735982432279',
                    orderNo: '354021731671873099',
                    orderType: 0,
                    orderSubType: 0,
                    orderStatus: 5,
                    totalAmount: '10010',
                    channelType: 0,
                    channelSource: '',
                    channelIdentity: '',
                    remark: '',
                    cancelType: null,
                    cancelReasonType: null,
                    cancelReason: null,
                    rightsType: null,
                    createTime: '1600350829291',
                    goods: {
                        id: '354021736133427225',
                        orderNo: null,
                        spuId: '3',
                        skuId: '135696670',
                        title:
                            '腾讯极光盒子4智能网络电视机顶盒6K千兆网络机顶盒4K高分辨率',
                        goodsPictureUrl:
                            'https://cdn-we-retail.ym.tencent.com/tsr/goods/dz-3b.png',
                        price: '10000',
                        buttonVOs: null,
                    },
                    buyerList:[{
                        id:"1111",
                        name:"王多鱼",
                        phoneNumber:"13364227822",
                        idNumber: "21133319990101444x"
                    }],
                    paymentVO: {
                        payStatus: 1,
                        amount: '20',
                        currency: null,
                        payType: null,
                        payWay: null,
                        payWayName: null,
                        interactId: null,
                        traceNo: null,
                        channelTrxNo: null,
                        period: null,
                        payTime: null,
                        paySuccessTime: null,
                    },
                    buttonVOs: [
                        {primary: false, type: 2, name: '取消订单'},
                        {primary: true, type: 1, name: '付款'},
                    ],
                    labelVOs: null,
                    couponAmount: null,
                    autoCancelTime: '1600352629291',
                    orderStatusName: '待付款',
                    orderSatusRemark: '需支付￥0.20',
                },
                {
                    uid: '88888888205468',
                    parentOrderNo: '132381532610540875',
                    orderId: '132381537256650240',
                    orderNo: '132381532610540875',
                    orderType: 0,
                    orderSubType: 0,
                    orderStatus: 10,
                    totalAmount: '76600',
                    paymentAmount: '36800',
                    channelType: 0,
                    channelSource: '',
                    channelIdentity: '',
                    remark: '',
                    cancelType: null,
                    cancelReasonType: null,
                    cancelReason: null,
                    rightsType: null,
                    createTime: '1587140043980',
                    goods: {
                        id: '132381537407645696',
                        orderNo: 'x2131231312',
                        spuId: '0',
                        skuId: '135676631',
                        title:
                            '白色短袖连衣裙荷叶边裙摆宽松韩版休闲纯白清爽优雅连衣裙',
                        goodsPictureUrl:
                            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
                        price: '40000',
                        tagPrice: null,
                        tagText: null,
                        outCode: null,
                        labelVOs: null,
                        buttonVOs: null,
                    },
                    buyerList:[{
                        id:"1111",
                        name:"王多鱼",
                        phoneNumber:"13364227822",
                        idNumber: "21133319990101444x"
                    },{
                        id:"1111",
                        name:"李多鱼",
                        phoneNumber:"13364227822",
                        idNumber: "21133319990101444x"
                    }],
                    paymentVO: {
                        payStatus: 1,
                        amount: '36800',
                        currency: null,
                        payType: null,
                        payWay: null,
                        payWayName: null,
                        interactId: null,
                        traceNo: null,
                        channelTrxNo: null,
                        period: null,
                        payTime: null,
                        paySuccessTime: null,
                    },
                    buttonVOs: [
                    ],
                    labelVOs: null,
                    couponAmount: null,
                    autoCancelTime: null,
                    orderStatusName: '已取消(未支付)',
                    orderSatusRemark: null,
                },
                {
                    uid: '88888888205468',
                    parentOrderNo: '132222623132329291',
                    orderId: '132222629674264064',
                    orderNo: '132222623132329291',
                    orderType: 0,
                    orderSubType: 0,
                    orderStatus: 40,
                    orderSubStatus: null,
                    totalAmount: '500400',
                    goodsAmount: '500400',
                    goodsAmountApp: '500400',
                    paymentAmount: '458600',
                    freightFee: '0',
                    packageFee: '0',
                    discountAmount: '41800',
                    channelType: 0,
                    channelSource: '',
                    channelIdentity: '',
                    remark: '',
                    cancelType: null,
                    cancelReasonType: null,
                    cancelReason: null,
                    rightsType: null,
                    createTime: '1587130572349',
                    goods: {
                        id: '132222629825259776',
                        orderNo: null,
                        spuId: '5',
                        skuId: '135691625',
                        roomId: null,
                        goodsMainType: 0,
                        goodsViceType: 0,
                        title:
                            '迷你便携高颜值蓝牙无线耳机立体声只能触控式操作简约立体声耳机',
                        goodsPictureUrl:
                            'https://cdn-we-retail.ym.tencent.com/tsr/goods/dz-2a.png',
                        price: '15900',
                        tagPrice: null,
                        tagText: null,
                        outCode: null,
                        labelVOs: null,
                        buttonVOs: null,
                    },
                    buyerList:[{
                        id:"1111",
                        name:"王多鱼",
                        phoneNumber:"13364227822",
                        idNumber: "21133319990101444x"
                    }],
                    paymentVO: {
                        payStatus: 1,
                        amount: '458600',
                        currency: null,
                        payType: null,
                        payWay: null,
                        payWayName: null,
                        interactId: null,
                        traceNo: null,
                        channelTrxNo: null,
                        period: null,
                        payTime: null,
                        paySuccessTime: null,
                    },
                    buttonVOs: [
                    ],
                    labelVOs: null,
                    invoiceVO: null,
                    couponAmount: null,
                    autoCancelTime: null,
                    orderStatusName: '交易完成',
                    orderSatusRemark: null,
                    logisticsLogVO: null,
                    invoiceStatus: null,
                    invoiceDesc: null,
                    invoiceUrl: null,
                },
                {
                    uid: '88888888205468',
                    parentOrderNo: '130862219672031307',
                    orderId: '130862224737571072',
                    orderNo: '130862219672031307',
                    orderType: 0,
                    orderSubType: 0,
                    orderStatus: 80,
                    orderSubStatus: null,
                    totalAmount: '298000',
                    goodsAmount: '298000',
                    goodsAmountApp: '298000',
                    paymentAmount: '263200',
                    discountAmount: '34800',
                    channelType: 0,
                    channelSource: '',
                    channelIdentity: '',
                    remark: '',
                    cancelType: null,
                    cancelReasonType: null,
                    cancelReason: null,
                    rightsType: null,
                    createTime: '1587049485899',
                    goods: {
                        id: '130862224922120960',
                        orderNo: null,
                        spuId: '0',
                        skuId: '135676631',
                        title:
                            '白色短袖连衣裙荷叶边裙摆宽松韩版休闲纯白清爽优雅连衣裙',
                        goodsPictureUrl:
                            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
                        price: '40000',
                        tagPrice: null,
                        tagText: null,
                        outCode: null,
                        labelVOs: null,
                        buttonVOs: null,
                    },
                    buyerList:[{
                        id:"1111",
                        name:"王多鱼",
                        phoneNumber:"13364227822",
                        idNumber: "21133319990101444x"
                    }],
                    paymentVO: {
                        payStatus: 1,
                        amount: '263200',
                        currency: null,
                        payType: null,
                        payWay: null,
                        payWayName: null,
                        interactId: null,
                        traceNo: null,
                        channelTrxNo: null,
                        period: null,
                        payTime: null,
                        paySuccessTime: null,
                    },
                    buttonVOs: null,
                    labelVOs: null,
                    invoiceVO: null,
                    couponAmount: null,
                    autoCancelTime: null,
                    orderStatusName: '已取消',
                    orderSatusRemark: null,
                    logisticsLogVO: null,
                    invoiceStatus: null,
                    invoiceDesc: null,
                    invoiceUrl: null,
                },
                {
                    uid: '88888888205468',
                    parentOrderNo: '130494472895208267',
                    orderId: '130494482155052032',
                    orderNo: '130494472895208267',
                    orderType: 0,
                    orderSubType: 0,
                    orderStatus: 80,
                    orderSubStatus: null,
                    totalAmount: '59700',
                    goodsAmount: '59700',
                    goodsAmountApp: '59700',
                    paymentAmount: '24900',
                    freightFee: '0',
                    packageFee: '0',
                    discountAmount: '34800',
                    channelType: 0,
                    channelSource: '',
                    channelIdentity: '',
                    remark: '',
                    cancelType: null,
                    cancelReasonType: null,
                    cancelReason: null,
                    rightsType: null,
                    createTime: '1587027566730',
                    goods: {
                        id: '130494482322824704',
                        orderNo: null,
                        spuId: '7',
                        skuId: '135691633',
                        roomId: null,
                        goodsMainType: 0,
                        goodsViceType: 0,
                        title:
                            '不锈钢刀叉勺套装家用西餐餐具ins简约耐用不锈钢金色银色可选',
                        goodsPictureUrl:
                            'https://cdn-we-retail.ym.tencent.com/tsr/goods/gh-2b.png',
                        price: '29900',
                        tagPrice: null,
                        tagText: null,
                        outCode: null,
                        labelVOs: null,
                        buttonVOs: null,
                    },
                    buyerList:[{
                        id:"1111",
                        name:"王多鱼",
                        phoneNumber:"13364227822",
                        idNumber: "21133319990101444x"
                    }],
                    paymentVO: {
                        payStatus: 1,
                        amount: '24900',
                        currency: null,
                        payType: null,
                        payWay: null,
                        payWayName: null,
                        interactId: null,
                        traceNo: null,
                        channelTrxNo: null,
                        period: null,
                        payTime: null,
                        paySuccessTime: null,
                    },
                    buttonVOs: null,
                    labelVOs: null,
                    invoiceVO: null,
                    couponAmount: null,
                    autoCancelTime: null,
                    orderStatusName: '已取消',
                    orderSatusRemark: null,
                    logisticsLogVO: null,
                    invoiceStatus: null,
                    invoiceDesc: null,
                    invoiceUrl: null,
                },
                {
                    uid: '88888888205468',
                    parentOrderNo: '130169571554503755',
                    orderId: '130169572291521792',
                    orderNo: '130169571554503755',
                    orderType: 0,
                    orderSubType: 0,
                    orderStatus: 50,
                    orderSubStatus: null,
                    totalAmount: '538000',
                    goodsAmount: '538000',
                    goodsAmountApp: '538000',
                    paymentAmount: '508200',
                    freightFee: '0',
                    packageFee: '0',
                    discountAmount: '29800',
                    channelType: 0,
                    channelSource: '',
                    channelIdentity: '',
                    remark: '',
                    cancelType: null,
                    cancelReasonType: null,
                    cancelReason: null,
                    rightsType: null,
                    createTime: '1587008200590',
                    goods: {
                        id: '130169572425740032',
                        orderNo: null,
                        spuId: '1',
                        skuId: '135691631',
                        title:
                            '纯色纯棉休闲圆领短袖T恤纯白亲肤厚柔软细腻面料纯白短袖套头T恤',
                        goodsPictureUrl:
                            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-08b.png',
                        price: '31900',
                        tagPrice: null,
                        tagText: null,
                        outCode: null,
                        labelVOs: null,
                        buttonVOs: [
                            {
                                primary: true,
                                type: 4,
                                name: '',
                            },
                        ],
                    },
                    buyerList:[{
                        id:"1111",
                        name:"王多鱼",
                        phoneNumber:"13364227822",
                        idNumber: "21133319990101444x"
                    }],
                    paymentVO: {
                        payStatus: 1,
                        amount: '508200',
                        currency: null,
                        payType: null,
                        payWay: null,
                        payWayName: null,
                        interactId: null,
                        traceNo: null,
                        channelTrxNo: null,
                        period: null,
                        payTime: null,
                        paySuccessTime: null,
                    },
                    buttonVOs: [
                    ],
                    labelVOs: null,
                    couponAmount: null,
                    autoCancelTime: null,
                    orderStatusName: '交易完成',
                    orderSatusRemark: null,
                    logisticsLogVO: null,
                    invoiceStatus: null,
                    invoiceDesc: null,
                    invoiceUrl: null,
                },
                {
                    uid: '88888888205468',
                    parentOrderNo: '130150835531421259',
                    orderId: '130150836385879808',
                    orderNo: '130150835531421259',
                    orderType: 0,
                    orderSubType: 0,
                    orderStatus: 50,
                    orderSubStatus: null,
                    totalAmount: '29800',
                    goodsAmount: '29800',
                    goodsAmountApp: '29800',
                    paymentAmount: '4000',
                    freightFee: '0',
                    packageFee: '0',
                    discountAmount: '25800',
                    channelType: 0,
                    channelSource: '',
                    channelIdentity: '',
                    remark: '',
                    cancelType: null,
                    cancelReasonType: null,
                    cancelReason: null,
                    rightsType: null,
                    createTime: '1587007083842',
                    goods: {
                        id: '130150836520098048',
                        orderNo: null,
                        spuId: '0',
                        skuId: '135681631',
                        roomId: null,
                        goodsMainType: 0,
                        goodsViceType: 0,
                        title:
                            '白色短袖连衣裙荷叶边裙摆宽松韩版休闲纯白清爽优雅连衣裙',
                        goodsPictureUrl:
                            'https://cdn-we-retail.ym.tencent.com/tsr/goods/nz-09a.png',
                        price: '40000',
                        buyQuantity: 1,
                        itemTotalAmount: '29800',
                        itemDiscountAmount: '25800',
                        itemPaymentAmount: '4000',
                        goodsPaymentPrice: '4000',
                        tagPrice: null,
                        tagText: null,
                        outCode: null,
                        labelVOs: null,
                        buttonVOs: null,
                    },
                    buyerList:[{
                        id:"1111",
                        name:"王多鱼",
                        phoneNumber:"13364227822",
                        idNumber: "21133319990101444x"
                    }],
                    logisticsVO: {
                        logisticsType: 1,
                        logisticsNo: '123',
                        logisticsStatus: null,
                        logisticsCompanyCode: 'yuantong',
                        logisticsCompanyName: '圆通速递',
                        receiverAddressId: '2',
                        provinceCode: '440000',
                        cityCode: '440300',
                        countryCode: '440306',
                        receiverProvince: '广东省',
                        receiverCity: '深圳市',
                        receiverCountry: '南山区',
                        receiverArea: '',
                        receiverAddress: '前海路333号阳光玫瑰园',
                        receiverPostCode: '',
                        receiverLongitude: '113.829127',
                        receiverLatitude: '22.713649',
                        receiverIdentity: '88888888205468',
                        receiverPhone: '17612345678',
                        receiverName: '平均线',
                        expectArrivalTime: null,
                        senderName: '',
                        senderPhone: '',
                        senderAddress: '',
                        sendTime: '1587008539953',
                        arrivalTime: '1588291200508',
                    },
                    paymentVO: {
                        payStatus: 1,
                        amount: '4000',
                        currency: null,
                        payType: null,
                        payWay: null,
                        payWayName: null,
                        interactId: null,
                        traceNo: null,
                        channelTrxNo: null,
                        period: null,
                        payTime: null,
                        paySuccessTime: null,
                    },
                    buttonVOs: [{primary: true, type: 6, name: '评价'}],
                    labelVOs: null,
                    invoiceVO: null,
                    couponAmount: null,
                    autoCancelTime: null,
                    orderStatusName: '交易完成',
                    orderSatusRemark: null,
                    logisticsLogVO: null,
                    invoiceStatus: null,
                    invoiceDesc: null,
                    invoiceUrl: null,
                },
            ],
        },
        code: 'Success',
        msg: null,
        requestId: mockReqId(),
        clientIp: mockIp(),
        rt: 113,
        success: true,
    };
    const {pageNum, pageSize, orderStatus} = params.parameter;
    // 实现筛选
    if (orderStatus > -1) {
        resp.data.orders = resp.data.orders.filter(
            (order) => order.orderStatus === orderStatus,
        );
    }
    // 实现分页
    resp.data.pageNum = pageNum;
    resp.data.pageSize = pageSize;
    resp.data.orders = resp.data.orders.slice(
        (pageNum - 1) * pageSize,
        pageNum * pageSize,
    );
    return resp;
}

export function genOrdersCount() {
    const resp = {
        data: [
            {tabType: 5, orderNum: 1},
            {tabType: 10, orderNum: 1},
            {tabType: 40, orderNum: 1},
            {tabType: 50, orderNum: 2},
        ],
        code: 'Success',
        msg: null,
        requestId: mockReqId(),
        clientIp: mockIp(),
        rt: 41,
        success: true,
    };
    return resp;
}
